apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: { { .Values.frontend.servicePort } }
      targetPort: { { .Values.frontend.servicePort } }
      nodePort: { { .Values.frontend.nodePort } }
