# Default values for cosmocloud-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

backend:
  image: shreybatra/sample-backend
  servicePort: 8000

frontend:
  image: shreybatra/sample-frontend
  servicePort: 5173
  nodePort: 31000

redis:
  image: redis
  servicePort: 6379

env:
  backendUrl: http://backend-svc:8000
  frontendUrl: http://frontend-svc:5173
  redisUri: http://redis-svc:6379
